version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  forms_executor:
    docker:
      - image: circleci/openjdk:11-stretch-node

jobs:
  build:
    executor: forms_executor
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Update permissions
          command: sudo chown -R circleci /usr/local/lib/node_modules
      - run:
          name: Build
          command: |
            java -version
            mvn -v
            mvn -B clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "pom.xml" }}
      - store_test_results:
          path: bundles/core/target/surefire-reports
      - store_artifacts:
          path: bundles/core/target/surefire-reports
      - codecov/upload:
          conf: .circleci/codecov.yml
          flags: unittests
 
  release:
    executor: forms_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Update permissions
          command: sudo chown -R circleci /usr/local/lib/node_modules
      - run:
          name: Release
          # Only performs a 'mvn deploy' after the 'mvn release:prepare' because circleCI
          # already checks out the git tag like 'mvn release:perform' would do.
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> /home/circleci/.npmrc
            echo $GPG_PRIVATE_KEY | base64 --decode | gpg --batch --import
            mvn -B -s /home/circleci/project/.circleci/settings.xml clean deploy -P release-sign-artifacts,adobe-public -Dskip-it
            rm -rf /home/circleci/.gnupg
            rm -rf /home/circleci/.npmrc

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^core-forms-components-reactor-\d+\.\d+\.\d+$/